development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: ccs
  username: ccs
  password: ccs
  host: 127.0.0.1
  port: 3306
  reconnect: true
